### ISSUE TITLE
Equality between local-date and local-date-time is not symmetric

### ISSUE THREAD

**Issue by dmarjenburgh** [andrewmcveigh/cljs-time#102]
I encountered this weird behaviour:

```clj
(def date1 (local-date 2017 1 1)) ;; Any date will do the same
(def date2 (local-date-time 2017 1 1))


(compare date1 date2) ;=> 0
(= date1 date2) .     ;=> true
(compare date2 date1) ;=> 0
(= date2 date1) .     ;=> false(!)
```

I don't know if this is an error in goog.date.DateTime or cljs-time.

**Comment by danielcompton** [comment]
This is intentional, dates and date-times are separate types. You can see the implementation in [extend.cljs](https://github.com/andrewmcveigh/cljs-time/blob/v0.5.1/src/cljs_time/extend.cljs#L23-L59). If you (and your dependencies) don't require `extend.cljs` then I think you might be able to compare dates and date times by relying on the [goog.date.DateTime#equals](https://github.com/google/closure-library/blob/v20170626/closure/goog/date/date.js#L1648-L1657) and [goog.date.Date#equals](https://github.com/google/closure-library/blob/v20170626/closure/goog/date/date.js#L1250-L1254) functions (though I haven't looked too closely at this).

In general, you don't want objects of different types comparing equal, except in very specific situations.

**Comment by andrewmcveigh** [comment]
Thanks for digging into this @danielcompton. IIRC, equality on goog.date objects has never worked in "the clojure way", and its behaviour has changed over the years. It's why `extend.cljs`[1] and `cljs-time.internal.core/=` [2] exist.

This can't be fixed in `cljs-time`, but @danielcompton's suggestion of requiring `cljs-time.extend` is probably the best thing you can do.

[1] https://github.com/andrewmcveigh/cljs-time/blob/v0.5.1/src/cljs_time/extend.cljs#L23-L59
[2] https://github.com/andrewmcveigh/cljs-time/blob/v0.5.1/src/cljs_time/internal/core.cljs#L18
